name: Build ReDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build redoc
      run: npx @redocly/cli build-docs openapi.yaml --output index.html
    - name: Build redoc for v2
      run:  npx @redocly/cli build-docs v2/openapi/fb-unified-openapi.yaml --output v2/docs.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: '.github,openapi.yaml,v2/openapi,v2/api-validator,assets,README.md'
